r"""
Blind FMC imaging of FIVE random sub-wavelength voids (no Born, no reference)
=============================================================================
Same blind workflow as ``deepwave_fmc_kirchhoff_blind.py`` -- a single
:mod:`deepwave` full-wave simulation, no Born modelling, no void-free reference
run, traveltime + amplitude tables generated by the pylops
:py:class:`pylops.waveeqprocessing.Kirchhoff` operator itself and passed back
via ``mode="byot"`` -- but now the aluminum plate contains **five randomly
placed air voids, each smaller than the 1.26 mm aluminum wavelength at 5 MHz**
(diameters 0.3--0.8 mm).

The preprocessing is identical and fully data-driven:

1. time-zero correction (known excitation delay);
2. zero-phase bandpass around the transducer band;
3. **common-offset median subtraction** -- still valid with several scatterers:
   each void diffraction stays localised in x, so the median over the 28+
   element pairs at a fixed offset estimates only the laterally invariant
   events (direct wave, back-wall echo, multiples);
4. direct-wave top mute + back-wall inspection gate (geometry/velocity only);
5. linear time gain.

Per-void localisation errors and peak/background contrasts quantify the
reconstruction. Outputs go to ``outputs/deepwave_fmc_blind_multi/``.
"""
import os
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from scipy.signal import butter, hilbert, sosfiltfilt

import deepwave
from deepwave import scalar

from pylops.utils.wavelets import ricker
from pylops.waveeqprocessing.kirchhoff import Kirchhoff

OUTDIR = os.path.join("outputs", "deepwave_fmc_blind_multi")
os.makedirs(OUTDIR, exist_ok=True)

# ---------------------------------------------------------------------------
# 1. True medium: aluminum plate, air backing, five random sub-wavelength voids
# ---------------------------------------------------------------------------
dx = 0.5e-4  # 0.05 mm grid spacing [m]
nx_s, nz_s = 800, 600  # 40 mm x 30 mm
xs = np.arange(nx_s) * dx
zs = np.arange(nz_s) * dx

V_ALU, V_AIR = 6300.0, 343.0
FREQ = 5.0e6
LAM_ALU = V_ALU / FREQ  # 1.26 mm
Z_BACK = 0.024  # plate back wall at 24 mm depth (air below)

vel_true = np.full((nx_s, nz_s), V_ALU, dtype=np.float32)
vel_true[:, zs >= Z_BACK] = V_AIR

# five random voids: diameters 0.3-0.8 mm (all < lambda), placed under the
# array aperture with a minimum separation so they are individually resolvable
rng = np.random.default_rng(7)
N_VOIDS = 5
MIN_SEP = 3.5e-3
X_RANGE = (0.008, 0.032)
Z_RANGE = (0.006, 0.021)
voids = []  # (cx, cz, r)
while len(voids) < N_VOIDS:
    cx = rng.uniform(*X_RANGE)
    cz = rng.uniform(*Z_RANGE)
    if all(np.hypot(cx - vx, cz - vz) >= MIN_SEP for vx, vz, _ in voids):
        r = 0.5 * rng.uniform(0.3e-3, 0.8e-3)
        voids.append((cx, cz, r))
voids.sort(key=lambda v: v[1])  # shallow to deep, for reporting

Xg, Zg = np.meshgrid(xs, zs, indexing="ij")
print("true voids (sorted by depth):")
for k, (cx, cz, r) in enumerate(voids):
    vel_true[(Xg - cx) ** 2 + (Zg - cz) ** 2 <= r**2] = V_AIR
    print(f"  #{k}: x = {cx * 1e3:6.2f} mm, z = {cz * 1e3:6.2f} mm, "
          f"d = {2 * r * 1e3:.2f} mm = {2 * r / LAM_ALU:.2f} lambda")

# ---------------------------------------------------------------------------
# 2. FMC acquisition geometry (32 elements, 1 mm pitch, inside the aluminum)
# ---------------------------------------------------------------------------
n_el = 32
pitch_cells = 20  # 1 mm pitch
x0_cells = 90  # first element at x = 4.5 mm
z_cells = 40  # element depth = 2 mm
elem_ix = x0_cells + np.arange(n_el) * pitch_cells
elem_iz = np.full(n_el, z_cells)
elem_x = elem_ix * dx
elem_z = elem_iz * dx

# ---------------------------------------------------------------------------
# 3. ONE deepwave simulation of the true medium (the only data we get)
# ---------------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"deepwave device: {device}")

dt = 5.0e-9  # 5 ns -> Courant 0.63 at 6300 m/s
nt = 2200  # 11 us record
peak_time = 1.5 / FREQ

src_amp = (
    deepwave.wavelets.ricker(FREQ, nt, dt, peak_time)
    .reshape(1, 1, -1)
    .repeat(n_el, 1, 1)
    .to(device)
)
src_loc = torch.tensor(
    np.stack([elem_iz, elem_ix], axis=-1)[:, None, :], dtype=torch.long, device=device
)
rec_loc = torch.tensor(
    np.broadcast_to(np.stack([elem_iz, elem_ix], axis=-1), (n_el, n_el, 2)).copy(),
    dtype=torch.long,
    device=device,
)

t0 = time.perf_counter()
out = scalar(
    torch.tensor(vel_true.T.copy(), device=device),
    dx,
    dt,
    source_amplitudes=src_amp,
    source_locations=src_loc,
    receiver_locations=rec_loc,
    accuracy=4,
    pml_width=20,
    pml_freq=FREQ,
)
fmc_raw = out[-1].cpu().numpy().astype(np.float64)  # (n_src, n_rec, nt)
print(f"deepwave FMC sim: {time.perf_counter() - t0:.1f} s, data {fmc_raw.shape}")

t = np.arange(nt) * dt

# ---------------------------------------------------------------------------
# 4. Blind preprocessing (identical to the single-void study)
# ---------------------------------------------------------------------------
# (a) time-zero correction
n0 = int(round(peak_time / dt))
fmc_t0 = np.concatenate(
    [fmc_raw[..., n0:], np.zeros((n_el, n_el, n0))], axis=-1
)

# (b) zero-phase bandpass around the 5 MHz transducer band
sos = butter(4, [2.5e6, 7.5e6], btype="bandpass", fs=1.0 / dt, output="sos")
fmc_bp = sosfiltfilt(sos, fmc_t0, axis=-1)

# (c) common-offset median subtraction
fmc_cos = fmc_bp.copy()
MIN_PAIRS = 4
for k in range(-(n_el - 1), n_el):
    ii = np.arange(max(0, -k), min(n_el, n_el - k))
    if len(ii) < MIN_PAIRS:
        fmc_cos[ii, ii + k, :] = 0.0
        continue
    med = np.median(fmc_bp[ii, ii + k, :], axis=0)
    fmc_cos[ii, ii + k, :] -= med

# (d) direct-wave top mute + back-wall inspection gate (cosine ramps)
T_PAD = 0.9e-6
T_RAMP = 0.3e-6
h_bw = 2.0 * (Z_BACK - elem_z[0])
mute = np.ones((n_el, n_el, nt))
for i in range(n_el):
    offs = np.abs(elem_x - elem_x[i])
    t_dir = offs / V_ALU + T_PAD
    t_bw = np.sqrt(h_bw**2 + offs**2) / V_ALU - 0.4e-6
    for j in range(n_el):
        up = np.clip((t - t_dir[j]) / T_RAMP, 0.0, 1.0)
        dn = np.clip((t_bw[j] - t) / T_RAMP, 0.0, 1.0)
        mute[i, j] = (0.5 - 0.5 * np.cos(np.pi * up)) * (0.5 - 0.5 * np.cos(np.pi * dn))
tgain = t / t[-1]
fmc_pre = fmc_cos * mute * tgain
fmc_mut = fmc_bp * mute * tgain  # mute+gain only, for comparison

# ---------------------------------------------------------------------------
# 5. Traveltime and amplitude tables FROM THE KIRCHHOFF OPERATOR (byot)
# ---------------------------------------------------------------------------
dxm = 1.0e-4  # 0.1 mm migration grid
nxm, nzm = nx_s // 2, nz_s // 2
xm = np.arange(nxm) * dxm
zm = np.arange(nzm) * dxm

srcs = np.vstack((elem_x, elem_z))
recs = np.vstack((elem_x, elem_z))
ns, nr = srcs.shape[1], recs.shape[1]

trav_srcs, trav_recs, dist_srcs, dist_recs, _, _ = Kirchhoff._traveltime_table(
    zm, xm, srcs, recs, V_ALU, mode="analytic"
)
eps = 1e-2 * (dist_srcs.max() + dist_recs.max())
amp_srcs = 1.0 / np.sqrt(dist_srcs + eps)
amp_recs = 1.0 / np.sqrt(dist_recs + eps)

wav, _, wavc = ricker(t[:121], f0=FREQ)
shot_recs = [np.arange(nr) for _ in range(ns)]
Op = Kirchhoff(
    zm, xm, t, srcs, recs, V_ALU, wav, wavc,
    mode="byot",
    trav=(trav_srcs, trav_recs),
    amp=(amp_srcs, amp_recs),
    dynamic=False,
    shot_recs=shot_recs,
    engine="numba",
)


def migrate(data):
    return (Op.H @ data.ravel()).reshape(nxm, nzm)


t0 = time.perf_counter()
m_raw = migrate(fmc_bp)
m_mut = migrate(fmc_mut)
m_pre = migrate(fmc_pre)
print(f"3 migrations: {time.perf_counter() - t0:.1f} s")

m_env = np.abs(hilbert(m_pre, axis=1))

# ---------------------------------------------------------------------------
# 6. Per-void localisation and contrast
# ---------------------------------------------------------------------------
Xm, Zm = np.meshgrid(xm, zm, indexing="ij")

# background = inside the inspection zone but >2 lambda away from every void
zone_mask = (Zm >= 0.005) & (Zm <= 0.022)
far_mask = zone_mask.copy()
for cx, cz, _ in voids:
    far_mask &= (Xm - cx) ** 2 + (Zm - cz) ** 2 > (2 * LAM_ALU) ** 2
bg_rms = np.sqrt((m_env[far_mask] ** 2).mean())

SEARCH_R = 1.5e-3  # peak search radius around each true void
print("\nPer-void blind-imaging quality (envelope image)")
print(f"  background RMS (inspection zone) = {bg_rms:.3e}")
results = []
for k, (cx, cz, r) in enumerate(voids):
    near = (Xm - cx) ** 2 + (Zm - cz) ** 2 <= SEARCH_R**2
    vals = np.where(near, m_env, 0.0)
    pk = np.unravel_index(np.argmax(vals), vals.shape)
    pk_x, pk_z, pk_v = xm[pk[0]], zm[pk[1]], vals[pk]
    err = np.hypot(pk_x - cx, pk_z - cz)
    contrast = pk_v / bg_rms
    results.append((pk_x, pk_z, err, contrast))
    print(f"  void #{k} (d={2 * r * 1e3:.2f} mm, {2 * r / LAM_ALU:.2f} lam) "
          f"at ({cx * 1e3:5.2f}, {cz * 1e3:5.2f}) mm -> peak "
          f"({pk_x * 1e3:5.2f}, {pk_z * 1e3:5.2f}) mm, "
          f"err = {err * 1e3:.2f} mm ({err / LAM_ALU:.2f} lam), "
          f"contrast = {contrast:.1f}x")
errs = np.array([r[2] for r in results])
print(f"  mean localisation error = {errs.mean() * 1e3:.2f} mm "
      f"({errs.mean() / LAM_ALU:.2f} lambda), max = {errs.max() * 1e3:.2f} mm")

# ---------------------------------------------------------------------------
# 7. Figures
# ---------------------------------------------------------------------------
ext_mm = (xs[0] * 1e3, xs[-1] * 1e3, zs[-1] * 1e3, zs[0] * 1e3)
ext_mig = (xm[0] * 1e3, xm[-1] * 1e3, zm[-1] * 1e3, zm[0] * 1e3)


def mark(a, label=False):
    a.scatter(elem_x * 1e3, elem_z * 1e3, marker="v", s=12, c="r", edgecolors="k",
              label="array" if label else None)
    for k, (cx, cz, r) in enumerate(voids):
        a.scatter(cx * 1e3, cz * 1e3, marker="o", s=70, facecolors="none",
                  edgecolors="lime", linewidths=1.4,
                  label="true voids" if (label and k == 0) else None)
    a.set_xlabel("x [mm]"), a.set_ylabel("z [mm]")


# (a) true model
fig, ax = plt.subplots(figsize=(8, 6))
im = ax.imshow(vel_true.T, cmap="viridis", extent=ext_mm, aspect="equal")
plt.colorbar(im, ax=ax, label="velocity [m/s]")
mark(ax, label=True)
for k, (cx, cz, r) in enumerate(voids):
    ax.annotate(f"#{k}", (cx * 1e3 + 0.7, cz * 1e3 - 0.7), color="w", fontsize=9)
ax.set_title("True model: aluminum plate, air backing, five sub-$\\lambda$ voids")
ax.legend(loc="lower right")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "velocity_true.png"), dpi=130)

# (b) preprocessing stages on the central shot gather
ishot = ns // 2
stages = [
    (fmc_bp[ishot], "(1) bandpassed total field"),
    (fmc_cos[ishot], "(2) + common-offset median subtraction"),
    (fmc_pre[ishot], "(3) + mutes + t gain"),
]
fig, axs = plt.subplots(1, 3, figsize=(15, 5), sharey=True)
for a, (g, title) in zip(axs, stages):
    gmax = np.percentile(np.abs(g), 99.5) + 1e-30
    a.imshow(g.T, cmap="gray", vmin=-gmax, vmax=gmax,
             extent=(0, nr, t[-1] * 1e6, t[0] * 1e6), aspect="auto")
    a.set_title(title, fontsize=10)
    a.set_xlabel("receiver index")
axs[0].set_ylabel("t [us]")
fig.suptitle(f"Blind preprocessing with five voids, shot #{ishot}")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "preprocessing_stages.png"), dpi=130)

# (c) migration images
fig, axs = plt.subplots(1, 4, figsize=(20, 5))
panels = [
    (m_raw, "(1) migrate raw total field", "gray_r"),
    (m_mut, "(2) mute + gain only", "gray_r"),
    (m_pre, "(3) full blind pipeline", "gray_r"),
    (m_env, "(3) envelope", "magma"),
]
for a, (img, title, cmap) in zip(axs, panels):
    mmax = np.percentile(np.abs(img), 99.8) + 1e-30
    vmin = 0.0 if cmap == "magma" else -mmax
    a.imshow(img.T, cmap=cmap, extent=ext_mig, aspect="equal",
             vmin=vmin, vmax=mmax)
    a.set_title(title, fontsize=10)
    mark(a)
fig.suptitle("Kirchhoff migration (byot trav+amp from the operator), five "
             "sub-wavelength voids -- no Born, no reference subtraction")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "migration_blind.png"), dpi=130)

# (d) per-void zooms on the envelope image
fig, axs = plt.subplots(1, N_VOIDS, figsize=(4 * N_VOIDS, 4.4))
vmax = np.percentile(m_env, 99.95)
zoom_mm = 2.5
for k, (a, (cx, cz, r)) in enumerate(zip(axs, voids)):
    a.imshow(m_env.T, cmap="magma", extent=ext_mig, aspect="equal",
             vmin=0, vmax=vmax)
    a.scatter(cx * 1e3, cz * 1e3, marker="o", s=80, facecolors="none",
              edgecolors="lime", linewidths=1.5)
    pk_x, pk_z, err, contrast = results[k]
    a.scatter(pk_x * 1e3, pk_z * 1e3, marker="+", s=90, c="cyan", linewidths=1.5)
    a.set_xlim(cx * 1e3 - zoom_mm, cx * 1e3 + zoom_mm)
    a.set_ylim(cz * 1e3 + zoom_mm, cz * 1e3 - zoom_mm)
    a.set_title(f"void #{k}: d = {2 * r * 1e3:.2f} mm\n"
                f"err {err * 1e3:.2f} mm, {contrast:.0f}x", fontsize=10)
    a.set_xlabel("x [mm]")
axs[0].set_ylabel("z [mm]")
fig.suptitle("Envelope zooms (green = true void, cyan + = image peak)")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "void_zooms.png"), dpi=130)

np.savez_compressed(
    os.path.join(OUTDIR, "results.npz"),
    vel_true=vel_true,
    fmc_raw=fmc_raw.astype(np.float32),
    fmc_pre=fmc_pre.astype(np.float32),
    m_raw=m_raw, m_mut=m_mut, m_pre=m_pre, m_env=m_env,
    xm=xm, zm=zm, elem_x=elem_x, elem_z=elem_z,
    voids=np.array(voids), t=t,
    peaks=np.array(results), bg_rms=bg_rms,
)
print(f"\nSaved figures and results.npz to {OUTDIR}/")
