r"""
Pipeline shoot-out on the five-void case: old conditionings vs blind pipeline
=============================================================================
The earlier deepwave/Kirchhoff studies tried several data conditionings before
migration. This script reruns all of them -- **except the Born-style
reference-subtraction, which needs a void-free twin simulation and is excluded
by design** -- on the exact same five-void sub-wavelength dataset as
``deepwave_fmc_kirchhoff_blind_multi.py`` and compares them with identical
metrics:

* **P1 raw total field** -- migrate the recording as-is (old baseline);
* **P2 hard mute + t^2 gain** -- the old conditioning: hard direct-wave top
  mute and a t^2 spreading gain, nothing else;
* **P3 envelope of total field** -- the old envelope variant applied to the
  raw recording before migration;
* **P4 envelope of mute + gain** -- the old envelope variant applied to P2;
* **P5 blind pipeline (new)** -- time-zero correction, bandpass,
  common-offset median subtraction, direct-wave mute + back-wall inspection
  gate, linear t gain.

Every pipeline is migrated with the *same* Kirchhoff operator
(``mode="byot"``, traveltime + 1/sqrt(dist) amplitude tables generated by the
operator itself) and scored on the envelope of its migration image: per-void
localisation error and peak/background contrast, with the same search radius
and background mask for all pipelines.

Outputs go to ``outputs/deepwave_fmc_blind_multi_compare/``.
"""
import os
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from scipy.signal import butter, hilbert, sosfiltfilt

import deepwave
from deepwave import scalar

from pylops.utils.wavelets import ricker
from pylops.waveeqprocessing.kirchhoff import Kirchhoff

OUTDIR = os.path.join("outputs", "deepwave_fmc_blind_multi_compare")
os.makedirs(OUTDIR, exist_ok=True)

# ---------------------------------------------------------------------------
# 1. Same five-void medium as deepwave_fmc_kirchhoff_blind_multi.py (seed 7)
# ---------------------------------------------------------------------------
dx = 0.5e-4
nx_s, nz_s = 800, 600
xs = np.arange(nx_s) * dx
zs = np.arange(nz_s) * dx

V_ALU, V_AIR = 6300.0, 343.0
FREQ = 5.0e6
LAM_ALU = V_ALU / FREQ
Z_BACK = 0.024

vel_true = np.full((nx_s, nz_s), V_ALU, dtype=np.float32)
vel_true[:, zs >= Z_BACK] = V_AIR

rng = np.random.default_rng(7)
N_VOIDS = 5
MIN_SEP = 3.5e-3
X_RANGE = (0.008, 0.032)
Z_RANGE = (0.006, 0.021)
voids = []
while len(voids) < N_VOIDS:
    cx = rng.uniform(*X_RANGE)
    cz = rng.uniform(*Z_RANGE)
    if all(np.hypot(cx - vx, cz - vz) >= MIN_SEP for vx, vz, _ in voids):
        r = 0.5 * rng.uniform(0.3e-3, 0.8e-3)
        voids.append((cx, cz, r))
voids.sort(key=lambda v: v[1])

Xg, Zg = np.meshgrid(xs, zs, indexing="ij")
for cx, cz, r in voids:
    vel_true[(Xg - cx) ** 2 + (Zg - cz) ** 2 <= r**2] = V_AIR

# ---------------------------------------------------------------------------
# 2. FMC geometry and ONE deepwave simulation
# ---------------------------------------------------------------------------
n_el = 32
elem_ix = 90 + np.arange(n_el) * 20
elem_iz = np.full(n_el, 40)
elem_x = elem_ix * dx
elem_z = elem_iz * dx

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dt = 5.0e-9
nt = 2200
peak_time = 1.5 / FREQ

src_amp = (
    deepwave.wavelets.ricker(FREQ, nt, dt, peak_time)
    .reshape(1, 1, -1)
    .repeat(n_el, 1, 1)
    .to(device)
)
src_loc = torch.tensor(
    np.stack([elem_iz, elem_ix], axis=-1)[:, None, :], dtype=torch.long, device=device
)
rec_loc = torch.tensor(
    np.broadcast_to(np.stack([elem_iz, elem_ix], axis=-1), (n_el, n_el, 2)).copy(),
    dtype=torch.long,
    device=device,
)
t0 = time.perf_counter()
out = scalar(
    torch.tensor(vel_true.T.copy(), device=device),
    dx, dt,
    source_amplitudes=src_amp,
    source_locations=src_loc,
    receiver_locations=rec_loc,
    accuracy=4, pml_width=20, pml_freq=FREQ,
)
fmc = out[-1].cpu().numpy().astype(np.float64)
print(f"deepwave FMC sim: {time.perf_counter() - t0:.1f} s")
t = np.arange(nt) * dt

# ---------------------------------------------------------------------------
# 3. The five pipelines
# ---------------------------------------------------------------------------
def env_t(d):
    return np.abs(hilbert(d, axis=-1))


# --- old hard mute + t^2 gain (as in deepwave_fmc_kirchhoff_single.py) ------
mute_old = np.ones((n_el, n_el, nt))
for i in range(n_el):
    tdir = np.abs(elem_x - elem_x[i]) / V_ALU + peak_time + 0.5e-6
    for j in range(n_el):
        mute_old[i, j, t < tdir[j]] = 0.0
tgain2 = (t / t[-1]) ** 2

d_p1 = fmc
d_p2 = fmc * mute_old * tgain2
d_p3 = env_t(fmc)
d_p4 = env_t(d_p2)

# --- new blind pipeline (as in deepwave_fmc_kirchhoff_blind_multi.py) -------
n0 = int(round(peak_time / dt))
fmc_t0 = np.concatenate([fmc[..., n0:], np.zeros((n_el, n_el, n0))], axis=-1)
sos = butter(4, [2.5e6, 7.5e6], btype="bandpass", fs=1.0 / dt, output="sos")
fmc_bp = sosfiltfilt(sos, fmc_t0, axis=-1)

fmc_cos = fmc_bp.copy()
MIN_PAIRS = 4
for k in range(-(n_el - 1), n_el):
    ii = np.arange(max(0, -k), min(n_el, n_el - k))
    if len(ii) < MIN_PAIRS:
        fmc_cos[ii, ii + k, :] = 0.0
        continue
    fmc_cos[ii, ii + k, :] -= np.median(fmc_bp[ii, ii + k, :], axis=0)

T_PAD, T_RAMP = 0.9e-6, 0.3e-6
h_bw = 2.0 * (Z_BACK - elem_z[0])
mute_new = np.ones((n_el, n_el, nt))
for i in range(n_el):
    offs = np.abs(elem_x - elem_x[i])
    t_dir = offs / V_ALU + T_PAD
    t_bw = np.sqrt(h_bw**2 + offs**2) / V_ALU - 0.4e-6
    for j in range(n_el):
        up = np.clip((t - t_dir[j]) / T_RAMP, 0.0, 1.0)
        dn = np.clip((t_bw[j] - t) / T_RAMP, 0.0, 1.0)
        mute_new[i, j] = (0.5 - 0.5 * np.cos(np.pi * up)) * (
            0.5 - 0.5 * np.cos(np.pi * dn)
        )
d_p5 = fmc_cos * mute_new * (t / t[-1])

pipelines = [
    ("P1 raw total field", d_p1),
    ("P2 hard mute + t$^2$ gain", d_p2),
    ("P3 envelope of total", d_p3),
    ("P4 envelope of mute+gain", d_p4),
    ("P5 blind pipeline (new)", d_p5),
]

# ---------------------------------------------------------------------------
# 4. One operator (byot trav+amp from the Kirchhoff operator), five migrations
# ---------------------------------------------------------------------------
dxm = 1.0e-4
nxm, nzm = nx_s // 2, nz_s // 2
xm = np.arange(nxm) * dxm
zm = np.arange(nzm) * dxm
srcs = np.vstack((elem_x, elem_z))
recs = np.vstack((elem_x, elem_z))
ns, nr = srcs.shape[1], recs.shape[1]

trav_srcs, trav_recs, dist_srcs, dist_recs, _, _ = Kirchhoff._traveltime_table(
    zm, xm, srcs, recs, V_ALU, mode="analytic"
)
eps = 1e-2 * (dist_srcs.max() + dist_recs.max())
amp_srcs = 1.0 / np.sqrt(dist_srcs + eps)
amp_recs = 1.0 / np.sqrt(dist_recs + eps)

wav, _, wavc = ricker(t[:121], f0=FREQ)
Op = Kirchhoff(
    zm, xm, t, srcs, recs, V_ALU, wav, wavc,
    mode="byot",
    trav=(trav_srcs, trav_recs),
    amp=(amp_srcs, amp_recs),
    dynamic=False,
    shot_recs=[np.arange(nr) for _ in range(ns)],
    engine="numba",
)

t0 = time.perf_counter()
images = [(Op.H @ d.ravel()).reshape(nxm, nzm) for _, d in pipelines]
print(f"5 migrations: {time.perf_counter() - t0:.1f} s")
envs = [np.abs(hilbert(m, axis=1)) for m in images]

# ---------------------------------------------------------------------------
# 5. Identical metrics for every pipeline
# ---------------------------------------------------------------------------
Xm, Zm = np.meshgrid(xm, zm, indexing="ij")
zone_mask = (Zm >= 0.005) & (Zm <= 0.022)
far_mask = zone_mask.copy()
for cx, cz, _ in voids:
    far_mask &= (Xm - cx) ** 2 + (Zm - cz) ** 2 > (2 * LAM_ALU) ** 2

SEARCH_R = 1.5e-3
table = []  # per pipeline: (errs[mm], contrasts)
print("\nPer-pipeline scores (same masks, search radius and metric for all)")
for (name, _), menv in zip(pipelines, envs):
    bg_rms = np.sqrt((menv[far_mask] ** 2).mean())
    errs, cons = [], []
    for cx, cz, r in voids:
        near = (Xm - cx) ** 2 + (Zm - cz) ** 2 <= SEARCH_R**2
        vals = np.where(near, menv, 0.0)
        pk = np.unravel_index(np.argmax(vals), vals.shape)
        errs.append(np.hypot(xm[pk[0]] - cx, zm[pk[1]] - cz))
        cons.append(vals[pk] / bg_rms)
    errs, cons = np.array(errs), np.array(cons)
    table.append((errs, cons))
    print(f"  {name:30s} mean err = {errs.mean() * 1e3:.2f} mm "
          f"({errs.mean() / LAM_ALU:.2f} lam), max err = {errs.max() * 1e3:.2f} mm, "
          f"contrast min/mean = {cons.min():.1f}x / {cons.mean():.1f}x")

# ---------------------------------------------------------------------------
# 6. Figures
# ---------------------------------------------------------------------------
ext_mig = (xm[0] * 1e3, xm[-1] * 1e3, zm[-1] * 1e3, zm[0] * 1e3)


def mark(a):
    a.scatter(elem_x * 1e3, elem_z * 1e3, marker="v", s=10, c="r", edgecolors="k")
    for cx, cz, r in voids:
        a.scatter(cx * 1e3, cz * 1e3, marker="o", s=60, facecolors="none",
                  edgecolors="lime", linewidths=1.2)
    a.set_xlabel("x [mm]")


# (a) envelope images of all five pipelines, each on its own scale
fig, axs = plt.subplots(1, 5, figsize=(22, 4.6))
for a, (name, _), menv, (errs, cons) in zip(axs, pipelines, envs, table):
    a.imshow(menv.T, cmap="magma", extent=ext_mig, aspect="equal",
             vmin=0, vmax=np.percentile(menv, 99.95))
    mark(a)
    a.set_title(f"{name}\nmean err {errs.mean() * 1e3:.2f} mm, "
                f"contrast {cons.mean():.0f}x", fontsize=10)
axs[0].set_ylabel("z [mm]")
fig.suptitle("Five-void case: envelope of the migration image for each "
             "pipeline (green = true voids)")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_envelopes.png"), dpi=130)

# (b) bipolar migration images for the signal-domain pipelines
fig, axs = plt.subplots(1, 5, figsize=(22, 4.6))
for a, (name, _), m in zip(axs, pipelines, images):
    mmax = np.percentile(np.abs(m), 99.8) + 1e-30
    a.imshow(m.T, cmap="gray_r", extent=ext_mig, aspect="equal",
             vmin=-mmax, vmax=mmax)
    mark(a)
    a.set_title(name, fontsize=10)
axs[0].set_ylabel("z [mm]")
fig.suptitle("Raw (bipolar) migration images, same pipelines")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_images.png"), dpi=130)

# (c) grouped bar chart: per-void contrast for each pipeline
fig, axs = plt.subplots(1, 2, figsize=(14, 4.8))
w = 0.15
idx = np.arange(N_VOIDS)
for p, ((name, _), (errs, cons)) in enumerate(zip(pipelines, table)):
    axs[0].bar(idx + (p - 2) * w, cons, w, label=name)
    axs[1].bar(idx + (p - 2) * w, errs * 1e3, w, label=name)
axs[0].set_yscale("log")
axs[0].set_ylabel("peak / background RMS")
axs[0].axhline(1.0, color="k", lw=0.8, ls="--")
axs[0].set_title("Per-void contrast (log scale; 1 = invisible)")
axs[1].set_ylabel("localisation error [mm]")
axs[1].axhline(LAM_ALU * 1e3, color="k", lw=0.8, ls="--")
axs[1].text(-0.4, LAM_ALU * 1e3 * 1.02, " $\\lambda$", fontsize=9)
axs[1].set_title("Per-void localisation error")
for a in axs:
    a.set_xticks(idx)
    a.set_xticklabels([f"void #{k}\nd={2 * r * 1e3:.2f} mm"
                       for k, (_, _, r) in enumerate(voids)], fontsize=8)
axs[0].legend(fontsize=8)
fig.suptitle("Pipeline comparison on the five sub-wavelength voids")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_scores.png"), dpi=130)

np.savez_compressed(
    os.path.join(OUTDIR, "results.npz"),
    images=np.array(images), envs=np.array(envs),
    errs=np.array([e for e, _ in table]), cons=np.array([c for _, c in table]),
    voids=np.array(voids), xm=xm, zm=zm,
    names=np.array([n for n, _ in pipelines]),
)
print(f"\nSaved figures and results.npz to {OUTDIR}/")
