r"""
Blind FMC imaging of FIVE random sub-wavelength voids (no Born, no reference)
=============================================================================
Same blind workflow as ``deepwave_fmc_kirchhoff_blind.py`` -- a single
:mod:`deepwave` full-wave simulation, no Born modelling, no void-free reference
run, traveltime + amplitude tables generated by the pylops
:py:class:`pylops.waveeqprocessing.Kirchhoff` operator itself and passed back
via ``mode="byot"`` -- but now the aluminum plate contains **five randomly
placed air voids, each smaller than the 1.26 mm aluminum wavelength at 5 MHz**
(diameters 0.3--0.8 mm). The void placement recipe is
:data:`fmc_blind_utils.FIVE_VOID_CASE`, shared with the pipeline shoot-out
script so both provably run on the same medium.

The preprocessing is the shared blind chain from :mod:`fmc_blind_utils`:

1. time-zero correction (known excitation delay);
2. zero-phase bandpass around the transducer band;
3. **common-offset median subtraction** -- still valid with several scatterers:
   each void diffraction stays localised in x, so the median over the 28+
   element pairs at a fixed offset estimates only the laterally invariant
   events (direct wave, back-wall echo, multiples);
4. direct-wave top mute + back-wall inspection gate (geometry/velocity only);
5. linear time gain.

Per-void localisation errors and peak/background contrasts quantify the
reconstruction. Outputs go to ``outputs/deepwave_fmc_blind_multi/``.
"""
import os
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert

from pylops.utils.wavelets import ricker
from pylops.waveeqprocessing.kirchhoff import Kirchhoff

from fmc_blind_utils import (
    CONTACT,
    FIVE_VOID_CASE,
    byot_tables,
    bandpass,
    carve_voids,
    common_offset_median_subtract,
    contact_gate_times,
    cosine_gate_cube,
    make_random_voids,
    simulate_fmc,
    time_zero_correct,
)

OUTDIR = os.path.join("outputs", "deepwave_fmc_blind_multi")
os.makedirs(OUTDIR, exist_ok=True)

# ---------------------------------------------------------------------------
# 1. True medium: aluminum plate, air backing, five random sub-wavelength voids
# ---------------------------------------------------------------------------
C = CONTACT
dx, nx_s, nz_s = C.dx, C.nx, C.nz
xs = np.arange(nx_s) * dx
zs = np.arange(nz_s) * dx

V_ALU, V_AIR, FREQ, Z_BACK = C.v_alu, C.v_air, C.freq, C.z_back
LAM_ALU = V_ALU / FREQ  # 1.26 mm

vel_true = np.full((nx_s, nz_s), V_ALU, dtype=np.float32)
vel_true[:, zs >= Z_BACK] = V_AIR

# five random voids: diameters 0.3-0.8 mm (all < lambda), placed under the
# array aperture with a minimum separation so they are individually resolvable
voids = make_random_voids(**FIVE_VOID_CASE)
N_VOIDS = len(voids)
carve_voids(vel_true, xs, zs, voids, V_AIR)
print("true voids (sorted by depth):")
for k, (cx, cz, r) in enumerate(voids):
    print(f"  #{k}: x = {cx * 1e3:6.2f} mm, z = {cz * 1e3:6.2f} mm, "
          f"d = {2 * r * 1e3:.2f} mm = {2 * r / LAM_ALU:.2f} lambda")

# ---------------------------------------------------------------------------
# 2. FMC acquisition geometry (32 elements, 1 mm pitch, inside the aluminum)
# ---------------------------------------------------------------------------
n_el = C.n_el
elem_ix = C.x0_cells + np.arange(n_el) * C.pitch_cells  # 1 mm pitch, x0=4.5 mm
elem_iz = np.full(n_el, C.z_cells)  # element depth = 2 mm
elem_x = elem_ix * dx
elem_z = elem_iz * dx

# ---------------------------------------------------------------------------
# 3. ONE deepwave simulation of the true medium (the only data we get)
# ---------------------------------------------------------------------------
dt, nt = C.dt, C.nt
peak_time = 1.5 / FREQ

t0 = time.perf_counter()
fmc_raw = simulate_fmc(vel_true, dx, dt, nt, elem_ix, elem_iz, FREQ, peak_time)
print(f"deepwave FMC sim: {time.perf_counter() - t0:.1f} s, data {fmc_raw.shape}")

t = np.arange(nt) * dt

# ---------------------------------------------------------------------------
# 4. Blind preprocessing (identical to the single-void study)
# ---------------------------------------------------------------------------
fmc_t0 = time_zero_correct(fmc_raw, peak_time, dt)
fmc_bp = bandpass(fmc_t0, dt)
fmc_cos = common_offset_median_subtract(fmc_bp)

T_PAD = 0.9e-6
T_RAMP = 0.3e-6
t_open, t_close = contact_gate_times(elem_x, elem_z, V_ALU, Z_BACK, T_PAD)
mute = cosine_gate_cube(t, t_open, t_close, T_RAMP)
tgain = t / t[-1]
fmc_pre = fmc_cos * mute * tgain
fmc_mut = fmc_bp * mute * tgain  # mute+gain only, for comparison

# ---------------------------------------------------------------------------
# 5. Traveltime and amplitude tables FROM THE KIRCHHOFF OPERATOR (byot)
# ---------------------------------------------------------------------------
dxm = 1.0e-4  # 0.1 mm migration grid
nxm, nzm = nx_s // 2, nz_s // 2
xm = np.arange(nxm) * dxm
zm = np.arange(nzm) * dxm

srcs = np.vstack((elem_x, elem_z))
recs = np.vstack((elem_x, elem_z))
ns, nr = srcs.shape[1], recs.shape[1]

trav_srcs, trav_recs, amp_srcs, amp_recs = byot_tables(zm, xm, srcs, recs, V_ALU)

wav, _, wavc = ricker(t[:121], f0=FREQ)
Op = Kirchhoff(
    zm, xm, t, srcs, recs, V_ALU, wav, wavc,
    mode="byot",
    trav=(trav_srcs, trav_recs),
    amp=(amp_srcs, amp_recs),
    dynamic=False,
    engine="numba",
)


def migrate(data):
    return (Op.H @ data.ravel()).reshape(nxm, nzm)


t0 = time.perf_counter()
m_raw = migrate(fmc_bp)
m_mut = migrate(fmc_mut)
m_pre = migrate(fmc_pre)
print(f"3 migrations: {time.perf_counter() - t0:.1f} s")

m_env = np.abs(hilbert(m_pre, axis=1))

# ---------------------------------------------------------------------------
# 6. Per-void localisation and contrast
# ---------------------------------------------------------------------------
Xm, Zm = np.meshgrid(xm, zm, indexing="ij")

# background = inside the inspection zone but >2 lambda away from every void
zone_mask = (Zm >= 0.005) & (Zm <= 0.022)
far_mask = zone_mask.copy()
for cx, cz, _ in voids:
    far_mask &= (Xm - cx) ** 2 + (Zm - cz) ** 2 > (2 * LAM_ALU) ** 2
bg_rms = np.sqrt((m_env[far_mask] ** 2).mean())

SEARCH_R = 1.5e-3  # peak search radius around each true void
print("\nPer-void blind-imaging quality (envelope image)")
print(f"  background RMS (inspection zone) = {bg_rms:.3e}")
results = []
for k, (cx, cz, r) in enumerate(voids):
    near = (Xm - cx) ** 2 + (Zm - cz) ** 2 <= SEARCH_R**2
    vals = np.where(near, m_env, 0.0)
    pk = np.unravel_index(np.argmax(vals), vals.shape)
    pk_x, pk_z, pk_v = xm[pk[0]], zm[pk[1]], vals[pk]
    err = np.hypot(pk_x - cx, pk_z - cz)
    contrast = pk_v / bg_rms
    results.append((pk_x, pk_z, err, contrast))
    print(f"  void #{k} (d={2 * r * 1e3:.2f} mm, {2 * r / LAM_ALU:.2f} lam) "
          f"at ({cx * 1e3:5.2f}, {cz * 1e3:5.2f}) mm -> peak "
          f"({pk_x * 1e3:5.2f}, {pk_z * 1e3:5.2f}) mm, "
          f"err = {err * 1e3:.2f} mm ({err / LAM_ALU:.2f} lam), "
          f"contrast = {contrast:.1f}x")
errs = np.array([r[2] for r in results])
print(f"  mean localisation error = {errs.mean() * 1e3:.2f} mm "
      f"({errs.mean() / LAM_ALU:.2f} lambda), max = {errs.max() * 1e3:.2f} mm")

# ---------------------------------------------------------------------------
# 7. Figures
# ---------------------------------------------------------------------------
ext_mm = (xs[0] * 1e3, xs[-1] * 1e3, zs[-1] * 1e3, zs[0] * 1e3)
ext_mig = (xm[0] * 1e3, xm[-1] * 1e3, zm[-1] * 1e3, zm[0] * 1e3)


def mark(a, label=False):
    a.scatter(elem_x * 1e3, elem_z * 1e3, marker="v", s=12, c="r", edgecolors="k",
              label="array" if label else None)
    for k, (cx, cz, r) in enumerate(voids):
        a.scatter(cx * 1e3, cz * 1e3, marker="o", s=70, facecolors="none",
                  edgecolors="lime", linewidths=1.4,
                  label="true voids" if (label and k == 0) else None)
    a.set_xlabel("x [mm]"), a.set_ylabel("z [mm]")


# (a) true model
fig, ax = plt.subplots(figsize=(8, 6))
im = ax.imshow(vel_true.T, cmap="viridis", extent=ext_mm, aspect="equal")
plt.colorbar(im, ax=ax, label="velocity [m/s]")
mark(ax, label=True)
for k, (cx, cz, r) in enumerate(voids):
    ax.annotate(f"#{k}", (cx * 1e3 + 0.7, cz * 1e3 - 0.7), color="w", fontsize=9)
ax.set_title("True model: aluminum plate, air backing, five sub-$\\lambda$ voids")
ax.legend(loc="lower right")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "velocity_true.png"), dpi=130)

# (b) preprocessing stages on the central shot gather
ishot = ns // 2
stages = [
    (fmc_bp[ishot], "(1) bandpassed total field"),
    (fmc_cos[ishot], "(2) + common-offset median subtraction"),
    (fmc_pre[ishot], "(3) + mutes + t gain"),
]
fig, axs = plt.subplots(1, 3, figsize=(15, 5), sharey=True)
for a, (g, title) in zip(axs, stages):
    gmax = np.percentile(np.abs(g), 99.5) + 1e-30
    a.imshow(g.T, cmap="gray", vmin=-gmax, vmax=gmax,
             extent=(0, nr, t[-1] * 1e6, t[0] * 1e6), aspect="auto")
    a.set_title(title, fontsize=10)
    a.set_xlabel("receiver index")
axs[0].set_ylabel("t [us]")
fig.suptitle(f"Blind preprocessing with five voids, shot #{ishot}")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "preprocessing_stages.png"), dpi=130)

# (c) migration images
fig, axs = plt.subplots(1, 4, figsize=(20, 5))
panels = [
    (m_raw, "(1) migrate raw total field", "gray_r"),
    (m_mut, "(2) mute + gain only", "gray_r"),
    (m_pre, "(3) full blind pipeline", "gray_r"),
    (m_env, "(3) envelope", "magma"),
]
for a, (img, title, cmap) in zip(axs, panels):
    mmax = np.percentile(np.abs(img), 99.8) + 1e-30
    vmin = 0.0 if cmap == "magma" else -mmax
    a.imshow(img.T, cmap=cmap, extent=ext_mig, aspect="equal",
             vmin=vmin, vmax=mmax)
    a.set_title(title, fontsize=10)
    mark(a)
fig.suptitle("Kirchhoff migration (byot trav+amp from the operator), five "
             "sub-wavelength voids -- no Born, no reference subtraction")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "migration_blind.png"), dpi=130)

# (d) per-void zooms on the envelope image
fig, axs = plt.subplots(1, N_VOIDS, figsize=(4 * N_VOIDS, 4.4))
vmax = np.percentile(m_env, 99.95)
zoom_mm = 2.5
for k, (a, (cx, cz, r)) in enumerate(zip(axs, voids)):
    a.imshow(m_env.T, cmap="magma", extent=ext_mig, aspect="equal",
             vmin=0, vmax=vmax)
    a.scatter(cx * 1e3, cz * 1e3, marker="o", s=80, facecolors="none",
              edgecolors="lime", linewidths=1.5)
    pk_x, pk_z, err, contrast = results[k]
    a.scatter(pk_x * 1e3, pk_z * 1e3, marker="+", s=90, c="cyan", linewidths=1.5)
    a.set_xlim(cx * 1e3 - zoom_mm, cx * 1e3 + zoom_mm)
    a.set_ylim(cz * 1e3 + zoom_mm, cz * 1e3 - zoom_mm)
    a.set_title(f"void #{k}: d = {2 * r * 1e3:.2f} mm\n"
                f"err {err * 1e3:.2f} mm, {contrast:.0f}x", fontsize=10)
    a.set_xlabel("x [mm]")
axs[0].set_ylabel("z [mm]")
fig.suptitle("Envelope zooms (green = true void, cyan + = image peak)")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "void_zooms.png"), dpi=130)

np.savez_compressed(
    os.path.join(OUTDIR, "results.npz"),
    vel_true=vel_true,
    fmc_raw=fmc_raw.astype(np.float32),
    fmc_pre=fmc_pre.astype(np.float32),
    m_raw=m_raw, m_mut=m_mut, m_pre=m_pre, m_env=m_env,
    xm=xm, zm=zm, elem_x=elem_x, elem_z=elem_z,
    voids=np.array(voids), t=t,
    peaks=np.array(results), bg_rms=bg_rms,
)
print(f"\nSaved figures and results.npz to {OUTDIR}/")
