r"""
Pipeline shoot-out on the five-void case: old conditionings vs blind pipeline
=============================================================================
The earlier deepwave/Kirchhoff studies tried several data conditionings before
migration. This script reruns all of them -- **except the Born-style
reference-subtraction, which needs a void-free twin simulation and is excluded
by design** -- on the same five-void sub-wavelength dataset as
``deepwave_fmc_kirchhoff_blind_multi.py`` and compares them with identical
metrics.

Two fairness rules make this an apples-to-apples comparison of the
*conditionings themselves*:

* **the dataset is provably identical**: the voids come from the shared
  :data:`fmc_blind_utils.FIVE_VOID_CASE` recipe, and the FMC data are loaded
  from the blind_multi run's ``results.npz`` when available (after checking
  the stored voids match); only if that file is absent is the simulation
  re-run;
* **the time-zero correction is applied to every pipeline up front**: the
  excitation delay is a known instrument property, not a conditioning choice.
  The historical runs of P1--P4 lacked this correction, which by itself
  biased their images ~0.9 mm deep; comparing without it would mix that
  trivially fixable bias into the pipeline scores.

The pipelines:

* **P1 raw total field** -- migrate the (time-zero-corrected) recording as-is;
* **P2 hard mute + t^2 gain** -- the old conditioning: hard direct-wave top
  mute and a t^2 spreading gain, nothing else;
* **P3 envelope of total field** -- the old envelope variant applied to the
  recording before migration;
* **P4 envelope of mute + gain** -- the old envelope variant applied to P2;
* **P5 blind pipeline (new)** -- bandpass, common-offset median subtraction,
  direct-wave mute + back-wall inspection gate, linear t gain (the shared
  chain from :mod:`fmc_blind_utils`).

Every pipeline is migrated with the *same* Kirchhoff operator
(``mode="byot"``, traveltime + 1/sqrt(dist) amplitude tables generated by the
operator itself) and scored on the envelope of its migration image: per-void
localisation error and peak/background contrast, with the same search radius
and background mask for all pipelines.

Outputs go to ``outputs/deepwave_fmc_blind_multi_compare/``.
"""
import os
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert

from pylops.utils.wavelets import ricker
from pylops.waveeqprocessing.kirchhoff import Kirchhoff

from fmc_blind_utils import (
    CONTACT,
    FIVE_VOID_CASE,
    byot_tables,
    bandpass,
    carve_voids,
    common_offset_median_subtract,
    contact_gate_times,
    cosine_gate_cube,
    make_random_voids,
    simulate_fmc,
    time_zero_correct,
)

OUTDIR = os.path.join("outputs", "deepwave_fmc_blind_multi_compare")
os.makedirs(OUTDIR, exist_ok=True)

# ---------------------------------------------------------------------------
# 1. The five-void dataset: same recipe as deepwave_fmc_kirchhoff_blind_multi
# ---------------------------------------------------------------------------
C = CONTACT
dx, nx_s, nz_s = C.dx, C.nx, C.nz
xs = np.arange(nx_s) * dx
zs = np.arange(nz_s) * dx

V_ALU, V_AIR, FREQ, Z_BACK = C.v_alu, C.v_air, C.freq, C.z_back
LAM_ALU = V_ALU / FREQ
dt, nt = C.dt, C.nt
peak_time = 1.5 / FREQ

voids = make_random_voids(**FIVE_VOID_CASE)
N_VOIDS = len(voids)

n_el = C.n_el
elem_ix = C.x0_cells + np.arange(n_el) * C.pitch_cells
elem_iz = np.full(n_el, C.z_cells)
elem_x = elem_ix * dx
elem_z = elem_iz * dx

# reuse the blind_multi run's data when available (verifying the stored voids
# match this recipe); otherwise simulate the same medium
multi_npz = os.path.join("outputs", "deepwave_fmc_blind_multi", "results.npz")
fmc = None
if os.path.exists(multi_npz):
    with np.load(multi_npz) as f:
        if "voids" in f and "fmc_raw" in f and np.allclose(f["voids"], voids):
            fmc = f["fmc_raw"].astype(np.float64)
            print(f"loaded FMC data from {multi_npz} (voids verified identical)")
        else:
            print(f"{multi_npz} does not match the shared void recipe; re-simulating")
if fmc is None:
    vel_true = np.full((nx_s, nz_s), V_ALU, dtype=np.float32)
    vel_true[:, zs >= Z_BACK] = V_AIR
    carve_voids(vel_true, xs, zs, voids, V_AIR)
    t0 = time.perf_counter()
    fmc = simulate_fmc(vel_true, dx, dt, nt, elem_ix, elem_iz, FREQ, peak_time)
    print(f"deepwave FMC sim: {time.perf_counter() - t0:.1f} s")
t = np.arange(nt) * dt

# ---------------------------------------------------------------------------
# 2. The five pipelines (all fed the time-zero-corrected data)
# ---------------------------------------------------------------------------
def env_t(d):
    return np.abs(hilbert(d, axis=-1))


# the excitation delay is a known instrument property: correct it for every
# pipeline so the shoot-out scores the conditionings, not a fixable bias
fmc_t0 = time_zero_correct(fmc, peak_time, dt)

# --- old hard mute + t^2 gain (as in deepwave_fmc_kirchhoff_single.py, minus
# the peak_time term its mute needed only because that data was uncorrected) --
tdir_old = np.abs(elem_x[:, None] - elem_x[None, :]) / V_ALU + 0.5e-6
mute_old = (t[None, None, :] >= tdir_old[:, :, None]).astype(float)
tgain2 = (t / t[-1]) ** 2

d_p1 = fmc_t0
d_p2 = fmc_t0 * mute_old * tgain2
d_p3 = env_t(fmc_t0)
d_p4 = env_t(d_p2)

# --- new blind pipeline (identical chain to deepwave_fmc_kirchhoff_blind_multi)
fmc_bp = bandpass(fmc_t0, dt)
fmc_cos = common_offset_median_subtract(fmc_bp)
T_PAD, T_RAMP = 0.9e-6, 0.3e-6
t_open, t_close = contact_gate_times(elem_x, elem_z, V_ALU, Z_BACK, T_PAD)
mute_new = cosine_gate_cube(t, t_open, t_close, T_RAMP)
d_p5 = fmc_cos * mute_new * (t / t[-1])

pipelines = [
    ("P1 raw total field", d_p1),
    ("P2 hard mute + t$^2$ gain", d_p2),
    ("P3 envelope of total", d_p3),
    ("P4 envelope of mute+gain", d_p4),
    ("P5 blind pipeline (new)", d_p5),
]

# ---------------------------------------------------------------------------
# 3. One operator (byot trav+amp from the Kirchhoff operator), five migrations
# ---------------------------------------------------------------------------
dxm = 1.0e-4
nxm, nzm = nx_s // 2, nz_s // 2
xm = np.arange(nxm) * dxm
zm = np.arange(nzm) * dxm
srcs = np.vstack((elem_x, elem_z))
recs = np.vstack((elem_x, elem_z))
ns, nr = srcs.shape[1], recs.shape[1]

trav_srcs, trav_recs, amp_srcs, amp_recs = byot_tables(zm, xm, srcs, recs, V_ALU)

wav, _, wavc = ricker(t[:121], f0=FREQ)
Op = Kirchhoff(
    zm, xm, t, srcs, recs, V_ALU, wav, wavc,
    mode="byot",
    trav=(trav_srcs, trav_recs),
    amp=(amp_srcs, amp_recs),
    dynamic=False,
    engine="numba",
)

t0 = time.perf_counter()
images = [(Op.H @ d.ravel()).reshape(nxm, nzm) for _, d in pipelines]
print(f"5 migrations: {time.perf_counter() - t0:.1f} s")
envs = [np.abs(hilbert(m, axis=1)) for m in images]

# ---------------------------------------------------------------------------
# 4. Identical metrics for every pipeline
# ---------------------------------------------------------------------------
Xm, Zm = np.meshgrid(xm, zm, indexing="ij")
zone_mask = (Zm >= 0.005) & (Zm <= 0.022)
far_mask = zone_mask.copy()
for cx, cz, _ in voids:
    far_mask &= (Xm - cx) ** 2 + (Zm - cz) ** 2 > (2 * LAM_ALU) ** 2

SEARCH_R = 1.5e-3
table = []  # per pipeline: (errs[mm], contrasts)
print("\nPer-pipeline scores (same masks, search radius and metric for all)")
for (name, _), menv in zip(pipelines, envs):
    bg_rms = np.sqrt((menv[far_mask] ** 2).mean())
    errs, cons = [], []
    for cx, cz, r in voids:
        near = (Xm - cx) ** 2 + (Zm - cz) ** 2 <= SEARCH_R**2
        vals = np.where(near, menv, 0.0)
        pk = np.unravel_index(np.argmax(vals), vals.shape)
        errs.append(np.hypot(xm[pk[0]] - cx, zm[pk[1]] - cz))
        cons.append(vals[pk] / bg_rms)
    errs, cons = np.array(errs), np.array(cons)
    table.append((errs, cons))
    print(f"  {name:30s} mean err = {errs.mean() * 1e3:.2f} mm "
          f"({errs.mean() / LAM_ALU:.2f} lam), max err = {errs.max() * 1e3:.2f} mm, "
          f"contrast min/mean = {cons.min():.1f}x / {cons.mean():.1f}x")

# ---------------------------------------------------------------------------
# 5. Figures
# ---------------------------------------------------------------------------
ext_mig = (xm[0] * 1e3, xm[-1] * 1e3, zm[-1] * 1e3, zm[0] * 1e3)


def mark(a):
    a.scatter(elem_x * 1e3, elem_z * 1e3, marker="v", s=10, c="r", edgecolors="k")
    for cx, cz, r in voids:
        a.scatter(cx * 1e3, cz * 1e3, marker="o", s=60, facecolors="none",
                  edgecolors="lime", linewidths=1.2)
    a.set_xlabel("x [mm]")


# (a) envelope images of all five pipelines, each on its own scale
fig, axs = plt.subplots(1, 5, figsize=(22, 4.6))
for a, (name, _), menv, (errs, cons) in zip(axs, pipelines, envs, table):
    a.imshow(menv.T, cmap="magma", extent=ext_mig, aspect="equal",
             vmin=0, vmax=np.percentile(menv, 99.95))
    mark(a)
    a.set_title(f"{name}\nmean err {errs.mean() * 1e3:.2f} mm, "
                f"contrast {cons.mean():.0f}x", fontsize=10)
axs[0].set_ylabel("z [mm]")
fig.suptitle("Five-void case: envelope of the migration image for each "
             "pipeline (green = true voids; time-zero corrected for all)")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_envelopes.png"), dpi=130)

# (b) bipolar migration images for the signal-domain pipelines
fig, axs = plt.subplots(1, 5, figsize=(22, 4.6))
for a, (name, _), m in zip(axs, pipelines, images):
    mmax = np.percentile(np.abs(m), 99.8) + 1e-30
    a.imshow(m.T, cmap="gray_r", extent=ext_mig, aspect="equal",
             vmin=-mmax, vmax=mmax)
    mark(a)
    a.set_title(name, fontsize=10)
axs[0].set_ylabel("z [mm]")
fig.suptitle("Raw (bipolar) migration images, same pipelines")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_images.png"), dpi=130)

# (c) grouped bar chart: per-void contrast for each pipeline
fig, axs = plt.subplots(1, 2, figsize=(14, 4.8))
w = 0.15
idx = np.arange(N_VOIDS)
for p, ((name, _), (errs, cons)) in enumerate(zip(pipelines, table)):
    axs[0].bar(idx + (p - 2) * w, cons, w, label=name)
    axs[1].bar(idx + (p - 2) * w, errs * 1e3, w, label=name)
axs[0].set_yscale("log")
axs[0].set_ylabel("peak / background RMS")
axs[0].axhline(1.0, color="k", lw=0.8, ls="--")
axs[0].set_title("Per-void contrast (log scale; 1 = invisible)")
axs[1].set_ylabel("localisation error [mm]")
axs[1].axhline(LAM_ALU * 1e3, color="k", lw=0.8, ls="--")
axs[1].text(-0.4, LAM_ALU * 1e3 * 1.02, " $\\lambda$", fontsize=9)
axs[1].set_title("Per-void localisation error")
for a in axs:
    a.set_xticks(idx)
    a.set_xticklabels([f"void #{k}\nd={2 * r * 1e3:.2f} mm"
                       for k, (_, _, r) in enumerate(voids)], fontsize=8)
axs[0].legend(fontsize=8)
fig.suptitle("Pipeline comparison on the five sub-wavelength voids "
             "(time-zero correction applied to all pipelines)")
fig.tight_layout()
fig.savefig(os.path.join(OUTDIR, "pipeline_scores.png"), dpi=130)

np.savez_compressed(
    os.path.join(OUTDIR, "results.npz"),
    images=np.array(images), envs=np.array(envs),
    errs=np.array([e for e, _ in table]), cons=np.array([c for _, c in table]),
    voids=np.array(voids), xm=xm, zm=zm,
    names=np.array([n for n, _ in pipelines]),
)
print(f"\nSaved figures and results.npz to {OUTDIR}/")
